In [1]:

import numpy as new

In [7]:
new_array=new.array([[1,2,3],[5,6,7]])
print(new_array)

[[1 2 3]
 [5 6 7]]


In [15]:
a=new.array([[0,1,2],[3,4,5],[6,7,8,]])
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
a[2,2]

8

In [19]:
array=new.random.random((2,2))
print(array)

[[0.56937614 0.00753219]
 [0.0039249  0.57216464]]


In [23]:
array=new.random.randint(2,10, size=(2,4))
print(array)


[[3 9 9 9]
 [4 6 3 4]]


In [32]:
from array import *
def array_list(array_num):
    num_list = array_num.tolist() # list
    print(num_list)
  
# driver code
array_num = array('i', [7,34,6,7,6,7,9,0]) # array
array_list(array_num)

[7, 34, 6, 7, 6, 7, 9, 0]


In [46]:
from array import *
def array_list(array_num):
    num_list = array_num.tolist()
    print("num_list")
    
array_num = array ('i' , [12,45,767,90,0,0]) 
array_list(array_num)

num_list


In [51]:
array_num = array('i',[7,34,6,7,6,7,9,0]) # array
liste=array_num.tolist()

In [52]:
liste

[7, 34, 6, 7, 6, 7, 9, 0]

In [54]:
array=new.array([1,2,3,4,5,6,7,8])
liste=array.tolist()

In [55]:
liste

[1, 2, 3, 4, 5, 6, 7, 8]

In [60]:
array=new.array (([1,2,3],[4,5,6],[7,8,9]))
array= array.trace()


In [59]:
array

<function ndarray.trace>

In [61]:
array

15

In [72]:
array = new.array(([1,2],[3,5]))
   for i in array :
if array[i] >= 2 :
    print (array(i))



IndentationError: unexpected indent (3004427042.py, line 2)

In [101]:
colone=int (input("enter a number of colone : " ))
line=int (input("enter a number of line : " ))
             
array=new.random.randint (0,9 ,size=(10,10))
           
x=int (input('enter a nuber'))
liste=[]
       
for i in range (colone) :
       
    for j in range (line) :
       
        if array [i,j] > x :
       
            liste. append(array[i,j])
             

             
print(liste)            
             
             

enter a number of colone : jj


ValueError: invalid literal for int() with base 10: 'jj'

# QUETION 3

In [105]:
array=new.array([23,8,89,9,0])
x=int(input ("give A x :"))
print(array[array>x])


give A x :2
[23  8 89  9]


# questin4



In [109]:
array1=new.array([[1,2,3],[4,5,6],[7,5,9]])
array2=new.array([[4,2,3],[7,5,6],[7,2,9]])

array3=new.add(array1,array2)

In [110]:
array3

array([[ 5,  4,  6],
       [11, 10, 12],
       [14,  7, 18]])

In [8]:
array1=new.array([[1,2,3],[4,5,6],[7,5,9]])
a=new.mean(array1,axis=1)
print(a)
print(array1-a)

[2. 5. 7.]
[[-1. -3. -4.]
 [ 2.  0. -1.]
 [ 5.  0.  2.]]
